name: CI

on:
  repository_dispatch:
    types: [tests-report]
  push:

jobs:
  build-test-contract:
    name: Build and Test Contract
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install contract dependencies
        run: cd contract && npm i
      # TODO: uncomment when SDK JS new release is out
      # - name: Build contract
      #   run: cd contract && npm run build
      - name: Run Contract Tests
        run: cd contract && npm run test

  build-test-server:
    name: Build and Test Server
    runs-on: ubuntu-latest
    needs: build-test-contract
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Requirements
        run: cd server && pip install -r requirements.txt
      - name: Install JQ
        uses: sergeysova/jq-action@v2
      - name: Add Keys to Environment
        env:
          PB_KEY: ${{ secrets.PB_KEY }}
          PR_KEY: ${{ secrets.PR_KEY }}
        run: sh scripts/add-keys-to-env.sh
      - name: Run Source API Test
        run: python -m unittest server.tests.integration.api.test_coingecko
      - name: Run E2E Test
        run: python -m unittest server.tests.e2e.test_oracle
